version = 0.1
[default.deploy.parameters]
stack_name = "ProjectTest"
resolve_s3 = true
s3_prefix = "ProjectTest"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "POCNameParameter=\"Quinton Sloan\" EnvironmentParameter=\"dev\" TableNameParameter=\"EchoMessages\""
image_repositories = []
